version: '3.1'

services:
  db:
    build: .
    restart: always
    container_name: beer_shop_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: beer_shop_db
    ports:
      - "3306:3306"
    volumes:
      - beer_shop_data:/var/lib/mysql

volumes:
  beer_shop_data:
